#!/usr/bin/env python

import sys
import os

import insass

usage = '''
An indented SASS stylesheet compiler.

usage: sass2css sass [css]
'''

if len(sys.argv) < 2:
  print usage
  sys.exit(1)


if not os.path.isfile(sys.argv[1]):
  print "Error: {} not found".format(in_fname)
  sys.exit(1)

sass = sys.argv[1]
with open(sass) as f:
  in_text = f.read()

if insass.compile_scss:
  out_text = insass.compile(in_text)
  scss = os.path.splitext(sass)[0] + '.scss'
  with open(scss, 'w') as f:
    f.write(out_text)
  out_text = insass.compile_scss(out_text)
else:
  out_text = insass.compile(in_text)

if len(sys.argv) > 2:
  out_fname = sys.argv[2]
  with open(out_fname, 'w') as f:
    f.write(out_text)
else:
  print out_text

